

[ClassVersion("1.0.0")]
Class ChefConf_WebConfigProp
{
    [write]String Filter;
    [write]String PSPath;
    [write]String Name;
	[write]String Value;
	[write]String Location;
};

[ClassVersion("2.0.1"), FriendlyName("Website")]
class ChefConf_Website : OMI_BaseResource
{
  [Key] string Name;
  [required] string PhysicalPath;
  [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
  [write,ValueMap{"Started","Stopped"},Values{"Started", "Stopped"}] string State;
  [write, EmbeddedInstance("ChefConf_WebConfigProp"), Description("Hashtable containing Web Configuration Properties (Filter, PSPath, Name, Location, Value)")] string webConfigProp[];
  [write] string ApplicationPool;
  [read] string Id;
};